name: Web
on: [push]

jobs:
  auto-deploy:
    runs-on: netlxc
    steps:
      - name: kill-gunicorn
        run: pkill gunicorn || true
      - name: pull
        uses: actions/checkout@v4
      - name: sync-uv
        run: uv sync
      - name: deploy
        run: uv run gunicorn main:app --bind 0.0.0.0:8000