name: Web
on: [push]

jobs:
  auto-deploy:
    runs-on: netlxc
    steps:
      - name: kill-gunicorn
        run: pkill gunicorn || true
      - name: pull
        uses: actions/checkout@v4
      - name: sync-uv
        run: uv sync
      - name: deploy
        # https://stackoverflow.com/questions/818255/what-does-21-mean
        run: nohup uv run gunicorn main:app --bind 0.0.0.0:8000 > app.log 2>&1 &