name: Web
on:
  push:
    branches: master

jobs:
  auto-deploy:
    runs-on: RackDockerLXC
    steps:
      - name: pull
        uses: actions/checkout@v4
      - name: build-docker
        run: docker build -t web .
      - name: deploy
        run: setsid docker run -d -p 8000:8000 web